server:
  port: 8000

spring:
  application:
    name: api-gateway

  profiles:
    active: local

#  cloud:
#    gateway:
#      httpclient:
#        wiretap: true

logging:
  level:
    org.springframework.cloud.gateway: trace
    reactor.netty.http.server: DEBUG