

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://172.31.19.11
          predicates:
            - Path=/api/**
server:
  port: 8000